# Ficheiro: pubspec.yaml
# ----------------------
# Adicionadas as dependências para ícones (font_awesome_flutter)
# e para salvar as configurações localmente (shared_preferences).

name: monitoring_dashboard
description: Um painel para visualizar o status de dispositivos monitorados.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  intl: ^0.19.0
  provider: ^6.1.1  # <-- VERIFIQUE SE ESTA LINHA EXISTE
  shared_preferences: ^2.2.2 
  csv: ^6.0.0
  universal_html: ^2.2.4
  
  
  # Novo: Pacote para ícones (Java, Firefox, etc.).
  font_awesome_flutter: ^10.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

